#/home/u/altera/13.1/quartus/eda/sim_lib/altera_mf.v
#/mnt/c/intelFPGA_lite/19.1/quartus/eda/sim_lib/altera_mf.v

../altera_mf.v

../../rtl/alu.v 
../../rtl/branch.v 
../../rtl/common.vh 
../../rtl/cpu7_csr_byplog.v 
../../rtl/cpu7_csr.v 
../../rtl/cpu7_exu_eclbyplog_rs1.v 
../../rtl/cpu7_exu_eclbyplog.v 
../../rtl/cpu7_exu_ecl.v 
../../rtl/cpu7_exu.v 
../../rtl/cpu7_ifu_dec.v 
../../rtl/cpu7_ifu_fdp.v 
../../rtl/cpu7_ifu_imd.v 
../../rtl/cpu7_ifu_incr30.v 
../../rtl/cpu7_ifu.v 
../../rtl/cpu7_lsu.v 
../../rtl/cpu7_nocache.v 
../../rtl/decoded.vh 
../../rtl/decoder.v 
../../rtl/mul32x32.v 
../../rtl/mul64x64.v 
../../rtl/reg_file.v 
../../rtl/swrvr_clib.v 
../../rtl/swrvr_dlib.v 
../../rtl/defines.vh 
../../rtl/axi_sram_bridge.v 
../../rtl/axi_interface.v 
../../rtl/sram.v 
../../rtl/cpu.v 
../../rtl/top.v
../../tb/test14_csr_crmd_top_tb.v
